rootProject.name = "PhotoWidget"
include(":app")
include(":core:model")
include(":core:database")
include(":core:analysis")
include(":core:common")
include(":feature:about")
include(":feature:settings")
include(":feature:link")
include(":feature:main")
include(":feature:widget")
